import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {gql} from "@apollo/client";
import client from "../apollo-client";

export default function Home({products,hello}) {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    <a href="https://nextjs.org">{hello}</a>
                </h1>

                <p className={styles.description}>
                    Get started by editing{' '}
                    <code className={styles.code}>pages/index.js</code>
                </p>

                <div className={styles.grid}>
                    <ul>
                    {products.map(({name, price}, i) => (
                            <li key={i}>{name}{'------->   $'}{price}</li>
                    ))}
                    </ul>
                </div>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16}/>
          </span>
                </a>
            </footer>
        </div>
    )
}

export async function getServerSideProps() {
    const {data} = await client.query({
        query: gql`
            query Products{
                getProducts{
                    name
                    price
                }
                hello
            }
        `,
    });

    return {
        props: {
            products: data.getProducts,
            hello:data.hello
        },
    };
}
